export interface VsPageData {
  slug: string;
  competitor: string;
  metaTitle: string;
  metaDesc: string;
  h1: string;
  subtitle: string;
  competitorDesc: string;
  ourWins: { title: string; desc: string }[];
  theirWins: { title: string; desc: string }[];
  tableRows: { feature: string; us: string; them: string; usBetter: boolean }[];
  bottomLine: string;
}

export const vsPages: VsPageData[] = [
  {
    slug: 'jobber',
    competitor: 'Jobber',
    metaTitle: 'IndustryBossPro vs Jobber | Field Service Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs Jobber for field service management. See pricing, features, and why multi-industry operators choose IndustryBossPro.',
    h1: 'IndustryBossPro vs Jobber: Which Field Service Software Is Right for You?',
    subtitle: 'Both are solid platforms. Here\'s the honest difference between them.',
    competitorDesc: 'Jobber is a well-established field service platform used by thousands of contractors. It handles scheduling, invoicing, and client management well. It\'s generalist software designed for a wide range of service businesses.',
    ourWins: [
      { title: '$199 flat vs Jobber\'s tiered pricing', desc: 'Jobber charges $49–$349/month based on features and user count. IndustryBossPro is $199/month — everything included, unlimited users.' },
      { title: 'Pending Job Board built for field service', desc: 'Our split-panel board (scheduled jobs vs waiting-list jobs) is purpose-built for operators running recurring routes with seasonal and on-demand work.' },
      { title: 'Built for 9 specific industries', desc: 'IndustryBossPro is tailored for snow, pool, landscaping, irrigation, lawn chemicals, pest control, mosquito, fence, and mowing — with industry-specific workflows in each.' },
      { title: 'Chemical & compliance tracking included', desc: 'EPA-compliant application logging is built in for lawn chemical, pest, and mosquito companies. Jobber doesn\'t offer this.' },
    ],
    theirWins: [
      { title: 'Longer track record', desc: 'Jobber has been around since 2011 and has a large user base and extensive integrations.' },
      { title: 'Broader app marketplace', desc: 'Jobber has more third-party integrations available through their marketplace.' },
    ],
    tableRows: [
      { feature: 'Pricing', us: '$199/mo flat', them: '$49–$349/mo (tiered)', usBetter: true },
      { feature: 'Users included', us: 'Unlimited', them: 'Limited by plan', usBetter: true },
      { feature: 'Pending Job Board', us: 'Built-in (scheduled + waiting list)', them: 'Basic job list', usBetter: true },
      { feature: 'Chemical application logging', us: 'Yes — EPA compliant', them: 'No', usBetter: true },
      { feature: 'Industry-specific workflows', us: '9 industries', them: 'Generic', usBetter: true },
      { feature: 'Mobile app', us: 'Yes', them: 'Yes', usBetter: false },
      { feature: 'Invoicing & payments', us: 'Yes', them: 'Yes', usBetter: false },
      { feature: 'Third-party integrations', us: 'Core integrations', them: 'Larger marketplace', usBetter: false },
      { feature: 'Free trial', us: '14 days', them: '14 days', usBetter: false },
    ],
    bottomLine: 'If you\'re running a single general service business and want a platform with a long track record and large integration library, Jobber is worth considering. If you\'re in one of the 9 industries we serve and want purpose-built workflows, a flat rate, and a pending job board that actually works for your operation — IndustryBossPro is the better fit.',
  },
  {
    slug: 'servicetitan',
    competitor: 'ServiceTitan',
    metaTitle: 'IndustryBossPro vs ServiceTitan | Field Service Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs ServiceTitan. See the pricing difference and decide which platform fits your field service business.',
    h1: 'IndustryBossPro vs ServiceTitan: Enterprise Power vs Focused Simplicity',
    subtitle: 'ServiceTitan is built for large operations. IndustryBossPro is built for operators who want the same power without the enterprise price tag.',
    competitorDesc: 'ServiceTitan is a powerful enterprise field service platform used by large HVAC, plumbing, and electrical companies. It has deep functionality but is priced and designed for larger operations with significant IT resources.',
    ourWins: [
      { title: 'Transparent flat pricing vs enterprise contracts', desc: 'ServiceTitan doesn\'t publish pricing — it\'s enterprise contract negotiation. IndustryBossPro is $199/month, no negotiation required.' },
      { title: 'Faster setup and onboarding', desc: 'ServiceTitan implementations often take months. IndustryBossPro is set up and running same day.' },
      { title: 'Built for outdoor services, not HVAC', desc: 'ServiceTitan\'s core DNA is HVAC and plumbing. IndustryBossPro is purpose-built for outdoor field service industries.' },
      { title: 'No per-user fees or feature tiers', desc: 'Everything is included at $199/mo. No surprise add-ons for features you assumed were included.' },
    ],
    theirWins: [
      { title: 'Deeper enterprise features', desc: 'ServiceTitan has more advanced reporting, deeper accounting integrations, and enterprise-grade user permissioning.' },
      { title: 'Better for large call center operations', desc: 'ServiceTitan\'s dispatch and call center features are built for operations taking hundreds of inbound calls per day.' },
    ],
    tableRows: [
      { feature: 'Pricing', us: '$199/mo flat', them: 'Enterprise contract (undisclosed)', usBetter: true },
      { feature: 'Setup time', us: 'Same day', them: 'Weeks to months', usBetter: true },
      { feature: 'Target market', us: 'Outdoor field service (9 industries)', them: 'HVAC, plumbing, electrical', usBetter: true },
      { feature: 'Pending Job Board', us: 'Yes — purpose-built', them: 'Dispatch board', usBetter: true },
      { feature: 'Chemical logging', us: 'Yes', them: 'No', usBetter: true },
      { feature: 'Enterprise reporting', us: 'Standard', them: 'Advanced', usBetter: false },
      { feature: 'Accounting integrations', us: 'QuickBooks', them: 'Multiple deep integrations', usBetter: false },
      { feature: 'Call center features', us: 'Basic', them: 'Enterprise-grade', usBetter: false },
    ],
    bottomLine: 'ServiceTitan makes sense for large HVAC or plumbing operations that need enterprise-grade tooling and have an IT team to manage implementation. For outdoor field service operators in our 9 industries, IndustryBossPro gives you more relevant functionality at a fraction of the cost.',
  },
  {
    slug: 'housecall-pro',
    competitor: 'Housecall Pro',
    metaTitle: 'IndustryBossPro vs Housecall Pro | Field Service Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs Housecall Pro for field service scheduling, invoicing, and routing. See which fits your business.',
    h1: 'IndustryBossPro vs Housecall Pro: Which One Fits Your Field Service Business?',
    subtitle: 'Both handle the basics. Here\'s where we\'re different.',
    competitorDesc: 'Housecall Pro is a popular field service platform targeting home service businesses. It offers solid scheduling, invoicing, and mobile features at accessible price points.',
    ourWins: [
      { title: 'Flat $199 vs Housecall Pro\'s per-user pricing', desc: 'Housecall Pro charges per user and by feature tier. IndustryBossPro is one flat price — unlimited users, everything included.' },
      { title: 'Pending Job Board with waiting list', desc: 'Our waiting list feature is purpose-built for operators managing seasonal demand and recurring routes with variable scheduling.' },
      { title: 'Chemical application compliance', desc: 'Built-in EPA-compliant chemical logging for pest, lawn, and mosquito operators. Housecall Pro doesn\'t have this.' },
      { title: 'Industry-specific onboarding', desc: 'We know your industry. Setup guidance and workflows are built around how your specific business actually operates.' },
    ],
    theirWins: [
      { title: 'Strong consumer-facing booking tools', desc: 'Housecall Pro has polished online booking and consumer payment experiences.' },
      { title: 'Larger user community', desc: 'Housecall Pro has a large user community with forums and shared best practices.' },
    ],
    tableRows: [
      { feature: 'Pricing', us: '$199/mo flat', them: 'Per-user tiered pricing', usBetter: true },
      { feature: 'Unlimited users', us: 'Yes', them: 'No — per user', usBetter: true },
      { feature: 'Pending Job Board', us: 'Yes', them: 'Basic scheduling board', usBetter: true },
      { feature: 'Chemical logging', us: 'Yes', them: 'No', usBetter: true },
      { feature: 'Mobile app', us: 'Yes', them: 'Yes', usBetter: false },
      { feature: 'Online booking', us: 'Standard', them: 'Advanced consumer booking', usBetter: false },
      { feature: 'Invoicing & payments', us: 'Yes', them: 'Yes', usBetter: false },
      { feature: 'User community', us: 'Growing', them: 'Large', usBetter: false },
    ],
    bottomLine: 'Housecall Pro is a solid choice for general home service businesses that prioritize consumer-facing booking tools. If you\'re a specialist in one of our 9 outdoor service industries and want flat pricing, compliance logging, and a waiting list built into your workflow — IndustryBossPro is the better fit.',
  },
  {
    slug: 'fieldedge',
    competitor: 'FieldEdge',
    metaTitle: 'IndustryBossPro vs FieldEdge | Field Service Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs FieldEdge. See which platform is better for outdoor field service businesses.',
    h1: 'IndustryBossPro vs FieldEdge: Outdoor Service Focus vs HVAC Roots',
    subtitle: 'FieldEdge is built for HVAC. IndustryBossPro is built for outdoor field service.',
    competitorDesc: 'FieldEdge is a field service platform with strong HVAC and plumbing roots. It offers solid dispatch, invoicing, and service agreement management for home service companies.',
    ourWins: [
      { title: 'Purpose-built for outdoor field service', desc: 'IndustryBossPro is designed from the ground up for snow, landscaping, lawn care, pest control, pool service, and more.' },
      { title: 'Pending Job Board with waiting list', desc: 'Our split-panel job board handles seasonal demand surges and recurring route management in a way FieldEdge wasn\'t built for.' },
      { title: 'Chemical compliance tracking', desc: 'Built-in application logging for licensed chemical applicators. FieldEdge doesn\'t offer this.' },
      { title: 'Flat pricing transparency', desc: '$199/month flat. No surprises, no enterprise negotiations.' },
    ],
    theirWins: [
      { title: 'Stronger HVAC-specific features', desc: 'FieldEdge has deeper equipment tracking and service agreement features designed for HVAC service contracts.' },
      { title: 'QuickBooks integration depth', desc: 'FieldEdge\'s QuickBooks integration is more mature and full-featured.' },
    ],
    tableRows: [
      { feature: 'Industry focus', us: '9 outdoor field service industries', them: 'HVAC, plumbing, electrical', usBetter: true },
      { feature: 'Pending Job Board', us: 'Yes', them: 'Standard dispatch', usBetter: true },
      { feature: 'Chemical logging', us: 'Yes', them: 'No', usBetter: true },
      { feature: 'Flat pricing', us: '$199/mo', them: 'Tiered / custom', usBetter: true },
      { feature: 'HVAC equipment tracking', us: 'Not specialized', them: 'Yes — purpose-built', usBetter: false },
      { feature: 'QuickBooks integration', us: 'Yes', them: 'More mature', usBetter: false },
    ],
    bottomLine: 'If you\'re running an HVAC or mechanical service business, FieldEdge is likely a better fit. If you\'re in outdoor services — mowing, snow, chemicals, pest, pool — IndustryBossPro is purpose-built for your operation.',
  },
  {
    slug: 'workiz',
    competitor: 'Workiz',
    metaTitle: 'IndustryBossPro vs Workiz | Field Service Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs Workiz for field service scheduling, invoicing, and team management.',
    h1: 'IndustryBossPro vs Workiz: Which Field Service Platform Fits Your Operation?',
    subtitle: 'Both are modern platforms. Here\'s how they compare for outdoor service businesses.',
    competitorDesc: 'Workiz is a field service platform with strong phone and VoIP features alongside standard scheduling and invoicing functionality. It targets small to mid-sized service businesses.',
    ourWins: [
      { title: 'Pending Job Board is unmatched', desc: 'Workiz has a standard job board. IndustryBossPro\'s split scheduled/waiting-list board is purpose-built for recurring outdoor service routes.' },
      { title: 'Chemical compliance built in', desc: 'For pest, lawn, and mosquito operators, EPA-compliant chemical logging is a legal requirement. Workiz doesn\'t offer it. We do.' },
      { title: 'Industry-specific workflows', desc: 'IndustryBossPro is configured around the actual workflows of 9 outdoor service industries.' },
      { title: 'Flat pricing', desc: '$199/mo for everything. Workiz tiers features and charges per user on higher plans.' },
    ],
    theirWins: [
      { title: 'Built-in VoIP calling', desc: 'Workiz has integrated business phone features that IndustryBossPro doesn\'t offer.' },
      { title: 'Stronger call tracking', desc: 'Workiz tracks inbound calls and ties them to jobs — useful for businesses that rely heavily on inbound phone leads.' },
    ],
    tableRows: [
      { feature: 'Pending Job Board', us: 'Yes — scheduled + waiting list', them: 'Standard job list', usBetter: true },
      { feature: 'Chemical logging', us: 'Yes', them: 'No', usBetter: true },
      { feature: 'Industry-specific workflows', us: '9 industries', them: 'Generic', usBetter: true },
      { feature: 'Pricing', us: '$199/mo flat', them: 'Per-user tiered', usBetter: true },
      { feature: 'Built-in VoIP', us: 'No', them: 'Yes', usBetter: false },
      { feature: 'Call tracking', us: 'Basic', them: 'Advanced', usBetter: false },
      { feature: 'Mobile app', us: 'Yes', them: 'Yes', usBetter: false },
    ],
    bottomLine: 'If your business runs heavily on inbound phone calls and you want built-in VoIP, Workiz has a feature IndustryBossPro doesn\'t. If you\'re an outdoor service operator who needs a purpose-built pending job board, chemical compliance, and flat pricing — we\'re the better fit.',
  },
  {
    slug: 'servicem8',
    competitor: 'ServiceM8',
    metaTitle: 'IndustryBossPro vs ServiceM8 | Field Service Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs ServiceM8 for field service job management, scheduling, and invoicing.',
    h1: 'IndustryBossPro vs ServiceM8: Which Platform Handles Your Workflow Better?',
    subtitle: 'ServiceM8 is built on Apple. IndustryBossPro is built for outdoor field service operators on any device.',
    competitorDesc: 'ServiceM8 is a field service platform built specifically for Apple devices (iOS). It offers strong job management and invoicing for trade businesses in Australia and New Zealand, with growing US presence.',
    ourWins: [
      { title: 'Platform-agnostic — works on Android too', desc: 'ServiceM8 is iOS-only for the mobile app. IndustryBossPro works on any device, any OS.' },
      { title: 'Built for US outdoor field service', desc: 'ServiceM8\'s core market is Australian trades. IndustryBossPro is purpose-built for US outdoor service industries.' },
      { title: 'Pending Job Board', desc: 'Our split waiting-list/scheduled board has no equivalent in ServiceM8.' },
      { title: 'Chemical compliance logging', desc: 'US pest, lawn, and mosquito operators need EPA-compliant records. ServiceM8 doesn\'t offer this.' },
    ],
    theirWins: [
      { title: 'Strong iOS and Apple Watch integration', desc: 'ServiceM8\'s Apple ecosystem integration is polished for teams running entirely on iPhone.' },
      { title: 'Solid form and inspection tools', desc: 'ServiceM8\'s digital form builder is flexible for businesses needing custom inspection forms.' },
    ],
    tableRows: [
      { feature: 'Platform', us: 'Any device / OS', them: 'iOS only (mobile)', usBetter: true },
      { feature: 'US market focus', us: 'Yes', them: 'Primary market is AU/NZ', usBetter: true },
      { feature: 'Pending Job Board', us: 'Yes', them: 'No equivalent', usBetter: true },
      { feature: 'Chemical logging', us: 'Yes', them: 'No', usBetter: true },
      { feature: 'Apple Watch support', us: 'No', them: 'Yes', usBetter: false },
      { feature: 'Custom form builder', us: 'Standard', them: 'Advanced', usBetter: false },
    ],
    bottomLine: 'ServiceM8 is a solid choice for iOS-only teams in Australia running trade businesses. For US outdoor field service operators on mixed devices who need industry-specific workflows and chemical compliance — IndustryBossPro is the purpose-built choice.',
  },
  {
    slug: 'realgreen',
    competitor: 'RealGreen',
    metaTitle: 'IndustryBossPro vs RealGreen | Lawn Care Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs RealGreen for lawn care and chemical application software.',
    h1: 'IndustryBossPro vs RealGreen: Lawn Care Software Compared',
    subtitle: 'RealGreen owns the enterprise lawn care space. IndustryBossPro brings those capabilities to growing operators at a fraction of the price.',
    competitorDesc: 'RealGreen (by WorkWave) is an enterprise-grade lawn care software platform used by large chemical lawn care companies. It has deep functionality but is priced and scaled for large operations.',
    ourWins: [
      { title: 'Accessible pricing for growing operators', desc: 'RealGreen is enterprise-priced and often requires implementation fees. IndustryBossPro is $199/month, no setup fees.' },
      { title: 'Multi-industry from day one', desc: 'RealGreen is lawn care focused. IndustryBossPro covers 9 outdoor service industries — grow into mosquito, pest, snow, or irrigation without switching software.' },
      { title: 'Faster setup', desc: 'RealGreen implementations can take weeks. IndustryBossPro is live same day.' },
    ],
    theirWins: [
      { title: 'Deeper lawn care enterprise features', desc: 'RealGreen has more advanced route density optimization and enterprise-scale chemical program management.' },
      { title: 'Longer lawn care track record', desc: 'RealGreen has decades of lawn care-specific development behind it.' },
      { title: 'Telesales integration', desc: 'RealGreen\'s Customer Acquisition Platform has deep telesales features for large outbound sales teams.' },
    ],
    tableRows: [
      { feature: 'Pricing', us: '$199/mo flat', them: 'Enterprise contract', usBetter: true },
      { feature: 'Setup speed', us: 'Same day', them: 'Weeks', usBetter: true },
      { feature: 'Industries covered', us: '9 outdoor service industries', them: 'Lawn care focused', usBetter: true },
      { feature: 'Pending Job Board', us: 'Yes', them: 'Route management', usBetter: true },
      { feature: 'Route density optimization', us: 'Standard', them: 'Advanced enterprise', usBetter: false },
      { feature: 'Lawn care track record', us: 'Growing', them: 'Decades', usBetter: false },
      { feature: 'Telesales features', us: 'Basic', them: 'Enterprise-grade', usBetter: false },
    ],
    bottomLine: 'RealGreen is the right choice for large lawn care enterprises with hundreds of technicians and complex route optimization needs. For growing lawn care, pest, mosquito, and multi-industry operators who want professional-grade tools at an accessible price — IndustryBossPro is the move.',
  },
  {
    slug: 'service-autopilot',
    competitor: 'Service Autopilot',
    metaTitle: 'IndustryBossPro vs Service Autopilot | Field Service Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs Service Autopilot for lawn care, pest control, and field service automation.',
    h1: 'IndustryBossPro vs Service Autopilot: Which Does More for Your Field Service Business?',
    subtitle: 'Service Autopilot has deep automation. IndustryBossPro brings that power to 9 industries at a simpler price.',
    competitorDesc: 'Service Autopilot is a feature-rich field service platform with strong automation features for lawn care and snow removal companies. It has a passionate user base and deep workflow automation.',
    ourWins: [
      { title: 'Simpler pricing structure', desc: 'Service Autopilot has multiple tiers and add-ons. IndustryBossPro is $199/month — everything included.' },
      { title: '9 industry coverage', desc: 'Service Autopilot focuses on lawn care and snow. IndustryBossPro covers pest, pool, irrigation, mosquito, fence, and mowing too.' },
      { title: 'Pending Job Board waiting list', desc: 'Our waiting list feature is distinct from standard job boards and purpose-built for mixed scheduled/on-demand workflows.' },
      { title: 'Faster to learn', desc: 'Service Autopilot has a steep learning curve. IndustryBossPro is designed to be operational in hours, not weeks.' },
    ],
    theirWins: [
      { title: 'More mature automation', desc: 'Service Autopilot\'s "Automations" feature is more developed for complex multi-step business workflows.' },
      { title: 'Stronger community', desc: 'Service Autopilot has an active user community and coaching programs built around the platform.' },
    ],
    tableRows: [
      { feature: 'Pricing', us: '$199/mo flat', them: 'Multiple tiers + add-ons', usBetter: true },
      { feature: 'Industries covered', us: '9 outdoor industries', them: 'Lawn care, snow focused', usBetter: true },
      { feature: 'Pending Job Board', us: 'Yes — scheduled + waiting list', them: 'Standard job management', usBetter: true },
      { feature: 'Learning curve', us: 'Low', them: 'Steep', usBetter: true },
      { feature: 'Workflow automation depth', us: 'Standard', them: 'Advanced', usBetter: false },
      { feature: 'User community', us: 'Growing', them: 'Large and active', usBetter: false },
    ],
    bottomLine: 'If you\'re a lawn care or snow operator who wants to go deep on automation and has time to master a complex platform — Service Autopilot is worth evaluating. If you want a simpler, multi-industry platform that\'s live same day and covers all 9 of your service types — IndustryBossPro is your answer.',
  },
  {
    slug: 'singleops',
    competitor: 'SingleOps',
    metaTitle: 'IndustryBossPro vs SingleOps | Outdoor Service Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs SingleOps for landscaping, tree care, and outdoor service management.',
    h1: 'IndustryBossPro vs SingleOps: Outdoor Service Software Compared',
    subtitle: 'Both target outdoor service. Here\'s where they differ.',
    competitorDesc: 'SingleOps is an outdoor service platform targeting landscaping, tree care, and grounds maintenance companies. It offers strong proposal and job management features.',
    ourWins: [
      { title: '$199 flat vs SingleOps tiered pricing', desc: 'SingleOps prices by feature tier. IndustryBossPro is flat $199 — unlimited users, all features.' },
      { title: 'Broader industry coverage', desc: 'IndustryBossPro covers 9 industries including snow, pool, pest, mosquito, and irrigation — beyond SingleOps\' landscape focus.' },
      { title: 'Pending Job Board with waiting list', desc: 'Our split-panel waiting-list board is purpose-built for high-volume routing and seasonal demand management.' },
      { title: 'Chemical compliance logging', desc: 'Lawn care, pest, and mosquito operators get EPA-compliant application logging built in.' },
    ],
    theirWins: [
      { title: 'Stronger for tree care', desc: 'SingleOps has features specifically designed for tree care and arborist businesses that we don\'t have.' },
      { title: 'Deeper proposal tools', desc: 'SingleOps\' proposal builder is more polished for large landscape installation bids.' },
    ],
    tableRows: [
      { feature: 'Pricing', us: '$199/mo flat', them: 'Tiered pricing', usBetter: true },
      { feature: 'Industries covered', us: '9 outdoor industries', them: 'Landscaping, tree care', usBetter: true },
      { feature: 'Pending Job Board', us: 'Yes', them: 'Standard job management', usBetter: true },
      { feature: 'Chemical logging', us: 'Yes', them: 'No', usBetter: true },
      { feature: 'Tree care features', us: 'Basic', them: 'Purpose-built', usBetter: false },
      { feature: 'Proposal tools', us: 'Standard', them: 'Advanced', usBetter: false },
    ],
    bottomLine: 'SingleOps is the better choice for tree care and arborist companies who need specialized features. For landscapers, lawn chemical, pest, pool, snow, or mowing operators who want one platform for all 9 industries — IndustryBossPro covers more ground.',
  },
  {
    slug: 'aspire',
    competitor: 'Aspire',
    metaTitle: 'IndustryBossPro vs Aspire | Landscaping Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs Aspire for landscape and outdoor service business management.',
    h1: 'IndustryBossPro vs Aspire: Enterprise Landscaping vs All-Industry Field Service',
    subtitle: 'Aspire is the enterprise choice for large landscapers. IndustryBossPro covers more industries at a fraction of the cost.',
    competitorDesc: 'Aspire is an enterprise landscaping software platform used by large commercial landscape companies. It offers deep job costing, equipment management, and subcontractor management features.',
    ourWins: [
      { title: 'Accessible flat pricing', desc: 'Aspire is enterprise-priced and targets large landscape companies. IndustryBossPro is $199/month for operations of any size.' },
      { title: '9 industry coverage', desc: 'Aspire is landscaping-focused. IndustryBossPro covers snow, pool, pest, mosquito, lawn chemicals, irrigation, fence, and mowing too.' },
      { title: 'Simpler to implement', desc: 'Aspire implementations are complex and time-consuming. IndustryBossPro is operational same day.' },
    ],
    theirWins: [
      { title: 'Enterprise job costing depth', desc: 'Aspire\'s job costing for large commercial landscape contracts is far deeper than anything we offer.' },
      { title: 'Equipment and fleet management', desc: 'Aspire has strong fleet and equipment tracking built for large landscape operations with significant equipment assets.' },
      { title: 'Subcontractor management', desc: 'Aspire handles complex subcontractor relationships and billing at a level suited for large commercial accounts.' },
    ],
    tableRows: [
      { feature: 'Pricing', us: '$199/mo flat', them: 'Enterprise (undisclosed)', usBetter: true },
      { feature: 'Setup time', us: 'Same day', them: 'Weeks to months', usBetter: true },
      { feature: 'Industries covered', us: '9 outdoor industries', them: 'Landscaping focused', usBetter: true },
      { feature: 'Enterprise job costing', us: 'Standard', them: 'Deep enterprise', usBetter: false },
      { feature: 'Fleet management', us: 'Basic', them: 'Advanced', usBetter: false },
      { feature: 'Commercial subcontracting', us: 'Basic', them: 'Enterprise-grade', usBetter: false },
    ],
    bottomLine: 'Aspire is built for large commercial landscape companies running millions in revenue. If you\'re a growing landscape, mowing, snow, pest, or pool company who wants professional tools at a reasonable price — IndustryBossPro gives you everything you need without the enterprise overhead.',
  },
  {
    slug: 'lmn',
    competitor: 'LMN',
    metaTitle: 'IndustryBossPro vs LMN | Landscape Management Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs LMN for landscape business management, estimating, and scheduling.',
    h1: 'IndustryBossPro vs LMN: Landscape Software for Different Stages of Growth',
    subtitle: 'LMN excels at estimating and budgeting for landscape businesses. IndustryBossPro covers 9 industries end-to-end.',
    competitorDesc: 'LMN (Landscape Management Network) is a landscape-focused platform with strong budgeting, estimating, and time-tracking features. Popular with Canadian and US landscape companies.',
    ourWins: [
      { title: 'Multi-industry from day one', desc: 'LMN is landscape-only. IndustryBossPro covers snow, pest, pool, irrigation, mosquito, fence, and mowing — all in one platform.' },
      { title: 'Pending Job Board', desc: 'LMN\'s job management is solid but doesn\'t have our purpose-built waiting list for seasonal demand management.' },
      { title: 'Chemical compliance', desc: 'Lawn chemical, pest, and mosquito operators get EPA-compliant logging built in.' },
      { title: 'Flat predictable pricing', desc: '$199/month — no per-user fees, no feature tiers.' },
    ],
    theirWins: [
      { title: 'Stronger landscape estimating', desc: 'LMN\'s estimating tools with built-in production rates are excellent for landscape installation bids.' },
      { title: 'Budget vs actual tracking', desc: 'LMN\'s job budget tracking is more detailed for landscape companies managing complex job costs.' },
      { title: 'Time-tracking depth', desc: 'LMN\'s time tracking with production rate comparison is strong for landscape crews.' },
    ],
    tableRows: [
      { feature: 'Industry focus', us: '9 outdoor industries', them: 'Landscaping only', usBetter: true },
      { feature: 'Pending Job Board', us: 'Yes — with waiting list', them: 'Standard job board', usBetter: true },
      { feature: 'Chemical logging', us: 'Yes', them: 'No', usBetter: true },
      { feature: 'Pricing', us: '$199/mo flat', them: 'Per-user pricing', usBetter: true },
      { feature: 'Landscape estimating', us: 'Standard', them: 'Advanced with production rates', usBetter: false },
      { feature: 'Budget vs actual', us: 'Standard', them: 'More detailed', usBetter: false },
    ],
    bottomLine: 'LMN is the right choice for landscape companies who want deep estimating, budget tracking, and production rate management. For operators running multiple service lines who want one platform for everything — IndustryBossPro is the broader solution.',
  },
  {
    slug: 'kickserv',
    competitor: 'Kickserv',
    metaTitle: 'IndustryBossPro vs Kickserv | Field Service Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs Kickserv for field service scheduling, invoicing, and team management.',
    h1: 'IndustryBossPro vs Kickserv: Comparing Field Service Platforms',
    subtitle: 'Kickserv is a solid generalist platform. IndustryBossPro is purpose-built for 9 outdoor service industries.',
    competitorDesc: 'Kickserv is a field service management platform offering scheduling, CRM, invoicing, and mobile features for service businesses. It\'s a solid generalist option with accessible pricing.',
    ourWins: [
      { title: 'Industry-specific workflows', desc: 'Kickserv is generalist software. IndustryBossPro is built specifically for snow, landscaping, pest, pool, mosquito, irrigation, fence, mowing, and lawn chemicals.' },
      { title: 'Pending Job Board with waiting list', desc: 'Our waiting-list feature for managing seasonal demand is unique — Kickserv has a standard job board.' },
      { title: 'Chemical compliance logging', desc: 'Built-in EPA-compliant application records for licensed applicators. Kickserv doesn\'t offer this.' },
    ],
    theirWins: [
      { title: 'Lower entry price point', desc: 'Kickserv has lower-priced plans for very small operations just getting started.' },
      { title: 'Simpler for one-person operations', desc: 'For solo operators, Kickserv\'s interface can feel lighter to manage.' },
    ],
    tableRows: [
      { feature: 'Industry specificity', us: '9 outdoor industries', them: 'Generalist', usBetter: true },
      { feature: 'Pending Job Board', us: 'Yes — with waiting list', them: 'Standard job list', usBetter: true },
      { feature: 'Chemical logging', us: 'Yes', them: 'No', usBetter: true },
      { feature: 'Unlimited users at flat price', us: 'Yes', them: 'Per-user pricing', usBetter: true },
      { feature: 'Entry price point', us: '$199/mo', them: 'Lower for solo ops', usBetter: false },
    ],
    bottomLine: 'For solo operators just getting started who need the simplest possible tool at the lowest price — Kickserv is worth looking at. For any operation in our 9 industries that needs industry-specific workflows, compliance logging, and a pending job board — IndustryBossPro is the better long-term platform.',
  },
  {
    slug: 'mhelp-desk',
    competitor: 'mHelpDesk',
    metaTitle: 'IndustryBossPro vs mHelpDesk | Field Service Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs mHelpDesk for field service scheduling, job management, and billing.',
    h1: 'IndustryBossPro vs mHelpDesk: Which Field Service Platform Fits Your Business?',
    subtitle: 'mHelpDesk handles the basics well. IndustryBossPro handles everything an outdoor service operator actually needs.',
    competitorDesc: 'mHelpDesk is a field service platform offering job scheduling, invoicing, and customer management. It targets home service businesses and offers a generalist feature set.',
    ourWins: [
      { title: 'Purpose-built for 9 outdoor service industries', desc: 'mHelpDesk is generalist home service software. IndustryBossPro is built around the specific workflows of outdoor service operators.' },
      { title: 'Pending Job Board with waiting list', desc: 'Our scheduled/waiting-list split board is purpose-built for operators managing recurring routes with seasonal demand.' },
      { title: 'Chemical compliance', desc: 'Pest, lawn, and mosquito operators get built-in EPA-compliant logging. mHelpDesk doesn\'t offer this.' },
    ],
    theirWins: [
      { title: 'Google integration depth', desc: 'mHelpDesk has solid Google Calendar integration.' },
      { title: 'Simple pricing tiers', desc: 'mHelpDesk offers lower starting tiers for very small operations.' },
    ],
    tableRows: [
      { feature: 'Industry focus', us: '9 outdoor industries', them: 'General home service', usBetter: true },
      { feature: 'Pending Job Board', us: 'Yes — with waiting list', them: 'Standard', usBetter: true },
      { feature: 'Chemical logging', us: 'Yes', them: 'No', usBetter: true },
      { feature: 'Unlimited users', us: 'Yes', them: 'Per-user pricing', usBetter: true },
      { feature: 'Google Calendar integration', us: 'Standard', them: 'More mature', usBetter: false },
    ],
    bottomLine: 'mHelpDesk works for generalist home service businesses. For operators in snow, landscaping, pest, pool, lawn chemicals, irrigation, mosquito, fence, or mowing — IndustryBossPro is built specifically for your operation.',
  },
  {
    slug: 'commusoft',
    competitor: 'Commusoft',
    metaTitle: 'IndustryBossPro vs Commusoft | Field Service Software Comparison',
    metaDesc: 'Compare IndustryBossPro vs Commusoft for field service management, scheduling, and invoicing.',
    h1: 'IndustryBossPro vs Commusoft: UK Trades Platform vs US Outdoor Service',
    subtitle: 'Commusoft is built for UK trade businesses. IndustryBossPro is purpose-built for US outdoor field service.',
    competitorDesc: 'Commusoft is a UK-based field service platform primarily serving gas, plumbing, heating, and electrical contractors. It has expanded to the US market with its job management features.',
    ourWins: [
      { title: 'Built for US outdoor service', desc: 'Commusoft\'s core market and compliance framework is UK-based. IndustryBossPro is built for US outdoor service operators and US chemical compliance requirements.' },
      { title: 'Purpose-built for 9 outdoor industries', desc: 'Commusoft targets UK trade businesses. IndustryBossPro is purpose-built for US snow, landscaping, pest, pool, mosquito, and outdoor service.' },
      { title: 'Pending Job Board with waiting list', desc: 'Our split scheduled/waiting-list board has no equivalent in Commusoft.' },
      { title: 'Chemical compliance for US operators', desc: 'US pest, lawn, and mosquito applicators need EPA-compliant records. IndustryBossPro provides this by default.' },
    ],
    theirWins: [
      { title: 'Strong for UK trade businesses', desc: 'If you\'re a UK-based plumbing or heating company, Commusoft is purpose-built for your market.' },
      { title: 'Mature Gas Safe and compliance features', desc: 'Commusoft has deep UK regulatory compliance features for gas and heating companies.' },
    ],
    tableRows: [
      { feature: 'Market focus', us: 'US outdoor field service', them: 'UK trade businesses', usBetter: true },
      { feature: 'US chemical compliance', us: 'Yes', them: 'No', usBetter: true },
      { feature: 'Pending Job Board', us: 'Yes', them: 'No', usBetter: true },
      { feature: '9 outdoor service industries', us: 'Yes', them: 'No', usBetter: true },
      { feature: 'UK trade compliance', us: 'No', them: 'Yes', usBetter: false },
    ],
    bottomLine: 'Commusoft is the right choice for UK gas, plumbing, and heating businesses. For US outdoor service operators in snow, landscaping, pest, pool, lawn chemicals, mosquito, irrigation, fence, or mowing — IndustryBossPro is purpose-built for your market.',
  },
];

export function getVsPage(slug: string): VsPageData | undefined {
  return vsPages.find(p => p.slug === slug);
}

export function getAllVsSlugs(): string[] {
  return vsPages.map(p => p.slug);
}
